language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - pip install --upgrade pip
  - pip install -q -r requirements.txt
  - pip install -q -r requirements_test.txt
script:
  - nosetests
